### ISSUE TITLE
Add "restrict access" to "administer tarteocitron" permission

### ISSUE THREAD

**Issue by Rudloff** [systonic/tarteocitron#2]
The `administer tarteocitron` permission allows injecting arbitrary JS in the page that is then executed with `eval()`.
This has security implications and this permission should only be given to trusted users.

Permissions like this should have `restrict access` set to true in the `permissions.yml` file, so that Drupal can warn that the permission is dangerous when adding it to a role.

(I initially created a private issue on https://huntr.dev/bounties/dc24c435-dd71-4d14-9acc-987d29aba6dc/ but it looks like this only works if the security policy contains an e-mail address the report can be sent to.
Since this is not really a vulnerability and more of security best practice, I guess it can be discussed publicly here.)

**Comment by systonic** [comment]
Tanks, I added the parameter on permissions.
